name: Pull wiki

on:
  workflow_run:
    workflows: [Closed]
    types:
      - completed

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr.zip`, Buffer.from(download.data));
      - name: 'Unzip artifact'
        run: unzip pr.zip
      - name: Hello world action step
        uses: ./
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          personalToken: ${{ secrets.PERSONAL_TOKEN }}
