name: Closed

on:
  pull_request:
    types: [closed]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Save PR number
        run: |
          echo ${{ github.event.number }} > pr
      - uses: actions/upload-artifact@v3
        with:
          name: pr
          path: pr
